### ISSUE TITLE
CRA 및 라우팅 셋업

### ISSUE THREAD

**Issue by xoxwgys56** [Couch-Coders/6th-starbucks-fe#1]
### TODO

- [x] setup using CRA
- [x] add react-router
- [x] setup route
- [ ] change application name
- [ ] add website favicon

### prerequisite

- use `BrowserRouter`, `Routes`, `Route`
   - use react-router@6
- url prefix `/pages`
   - `<BrowserRouter basename="pages" ... />`

---

`prettier`를 추가해도 될까요? [PR](https://github.com/Couch-Coders/6th-starbucks-fe/pull/4)

**Comment by xoxwgys56** [comment]
`prettier`를 추가해도 될까요? [PR](https://github.com/Couch-Coders/6th-starbucks-fe/pull/4)

**Comment by xoxwgys56** [comment]
### TODO

- [ ] setup route

### prerequisite

- use `BrowserRouter`, `Switch`, `Route`
   - use react-router@5
- url prefix `/pages`
   - `<BrowserRouter basename="pages" ... />`

**Comment by xoxwgys56** [comment]
### NOTE

finished progress

**Comment by xoxwgys56** [comment]
### TODO

- [ ] change application name
- [ ] add website favicon
