### ISSUE TITLE
json-server 셋업 및 mock 데이터 만들기

### ISSUE THREAD

**Issue by xoxwgys56** [Couch-Coders/6th-starbucks-fe#2]
## TODO

- [x] setup [json-server](https://github.com/typicode/json-server#getting-started)
- [ ] generate mock data

### mock data

- 스타벅스 앱에서 수작업으로 가져오는 것으로..

**Comment by xoxwgys56** [comment]
### TODO

- [ ] implement API for FE
