### ISSUE TITLE
firebase 인증 토큰 및 구글 로그인 UI

### ISSUE THREAD

**Issue by xoxwgys56** [Couch-Coders/6th-starbucks-fe#6]
### TODO

- [x] implement banner (header)
- [x] add google SSO signin
- [ ] store session data
